language: generic 

sudo: reqiured
services:
  - docker

before_install:
  - docker build -t humoberdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true humoberdocker/react-test npm test

after_success:
  - docker build -t humoberdocker/multi-client ./client
  - docker build -t humoberdocker/multi-nginx ./nginx
  - docker build -t humoberdocker/multi-server ./server
  - docker build -t humoberdocker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push humoberdocker/multi-client
  - docker push humoberdocker/multi-nginx
  - docker push humoberdocker/multi-server
  - docker push humoberdocker/multi-worker